// Generated by gencpp from file verysmall/motor_speed.msg
// DO NOT EDIT!


#ifndef VERYSMALL_MESSAGE_MOTOR_SPEED_H
#define VERYSMALL_MESSAGE_MOTOR_SPEED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace verysmall
{
template <class ContainerAllocator>
struct motor_speed_
{
  typedef motor_speed_<ContainerAllocator> Type;

  motor_speed_()
    : vel_l(0)
    , vel_r(0)  {
    }
  motor_speed_(const ContainerAllocator& _alloc)
    : vel_l(0)
    , vel_r(0)  {
  (void)_alloc;
    }



   typedef int32_t _vel_l_type;
  _vel_l_type vel_l;

   typedef int32_t _vel_r_type;
  _vel_r_type vel_r;





  typedef boost::shared_ptr< ::verysmall::motor_speed_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::verysmall::motor_speed_<ContainerAllocator> const> ConstPtr;

}; // struct motor_speed_

typedef ::verysmall::motor_speed_<std::allocator<void> > motor_speed;

typedef boost::shared_ptr< ::verysmall::motor_speed > motor_speedPtr;
typedef boost::shared_ptr< ::verysmall::motor_speed const> motor_speedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::verysmall::motor_speed_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::verysmall::motor_speed_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace verysmall

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'verysmall': ['/home/marquesman/ararabots/src/verysmall/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::verysmall::motor_speed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::verysmall::motor_speed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::verysmall::motor_speed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::verysmall::motor_speed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::verysmall::motor_speed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::verysmall::motor_speed_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::verysmall::motor_speed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f2dd34999ee8b444344eaa77fc91500c";
  }

  static const char* value(const ::verysmall::motor_speed_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf2dd34999ee8b444ULL;
  static const uint64_t static_value2 = 0x344eaa77fc91500cULL;
};

template<class ContainerAllocator>
struct DataType< ::verysmall::motor_speed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "verysmall/motor_speed";
  }

  static const char* value(const ::verysmall::motor_speed_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::verysmall::motor_speed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32            vel_l\n\
int32            vel_r\n\
";
  }

  static const char* value(const ::verysmall::motor_speed_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::verysmall::motor_speed_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vel_l);
      stream.next(m.vel_r);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct motor_speed_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::verysmall::motor_speed_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::verysmall::motor_speed_<ContainerAllocator>& v)
  {
    s << indent << "vel_l: ";
    Printer<int32_t>::stream(s, indent + "  ", v.vel_l);
    s << indent << "vel_r: ";
    Printer<int32_t>::stream(s, indent + "  ", v.vel_r);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VERYSMALL_MESSAGE_MOTOR_SPEED_H
