// Generated by gencpp from file verysmall/comunication_topic.msg
// DO NOT EDIT!


#ifndef VERYSMALL_MESSAGE_COMUNICATION_TOPIC_H
#define VERYSMALL_MESSAGE_COMUNICATION_TOPIC_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <verysmall/motor_speed.h>

namespace verysmall
{
template <class ContainerAllocator>
struct comunication_topic_
{
  typedef comunication_topic_<ContainerAllocator> Type;

  comunication_topic_()
    : robot_id()
    , robots_speed()  {
      robot_id.assign(0);
  }
  comunication_topic_(const ContainerAllocator& _alloc)
    : robot_id()
    , robots_speed()  {
  (void)_alloc;
      robot_id.assign(0);

      robots_speed.assign( ::verysmall::motor_speed_<ContainerAllocator> (_alloc));
  }



   typedef boost::array<uint8_t, 10>  _robot_id_type;
  _robot_id_type robot_id;

   typedef boost::array< ::verysmall::motor_speed_<ContainerAllocator> , 10>  _robots_speed_type;
  _robots_speed_type robots_speed;





  typedef boost::shared_ptr< ::verysmall::comunication_topic_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::verysmall::comunication_topic_<ContainerAllocator> const> ConstPtr;

}; // struct comunication_topic_

typedef ::verysmall::comunication_topic_<std::allocator<void> > comunication_topic;

typedef boost::shared_ptr< ::verysmall::comunication_topic > comunication_topicPtr;
typedef boost::shared_ptr< ::verysmall::comunication_topic const> comunication_topicConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::verysmall::comunication_topic_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::verysmall::comunication_topic_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace verysmall

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'verysmall': ['/home/marquesman/ararabots/src/verysmall/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::verysmall::comunication_topic_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::verysmall::comunication_topic_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::verysmall::comunication_topic_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::verysmall::comunication_topic_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::verysmall::comunication_topic_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::verysmall::comunication_topic_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::verysmall::comunication_topic_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bcfc10b8d53657d2a18ba160b07bee7b";
  }

  static const char* value(const ::verysmall::comunication_topic_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbcfc10b8d53657d2ULL;
  static const uint64_t static_value2 = 0xa18ba160b07bee7bULL;
};

template<class ContainerAllocator>
struct DataType< ::verysmall::comunication_topic_<ContainerAllocator> >
{
  static const char* value()
  {
    return "verysmall/comunication_topic";
  }

  static const char* value(const ::verysmall::comunication_topic_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::verysmall::comunication_topic_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8[10]          robot_id\n\
motor_speed[10]    robots_speed\n\
================================================================================\n\
MSG: verysmall/motor_speed\n\
int32            vel_l\n\
int32            vel_r\n\
";
  }

  static const char* value(const ::verysmall::comunication_topic_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::verysmall::comunication_topic_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robot_id);
      stream.next(m.robots_speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct comunication_topic_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::verysmall::comunication_topic_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::verysmall::comunication_topic_<ContainerAllocator>& v)
  {
    s << indent << "robot_id[]" << std::endl;
    for (size_t i = 0; i < v.robot_id.size(); ++i)
    {
      s << indent << "  robot_id[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.robot_id[i]);
    }
    s << indent << "robots_speed[]" << std::endl;
    for (size_t i = 0; i < v.robots_speed.size(); ++i)
    {
      s << indent << "  robots_speed[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::verysmall::motor_speed_<ContainerAllocator> >::stream(s, indent + "    ", v.robots_speed[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // VERYSMALL_MESSAGE_COMUNICATION_TOPIC_H
