// Generated by gencpp from file verysmall/five_robot_pos.msg
// DO NOT EDIT!


#ifndef VERYSMALL_MESSAGE_FIVE_ROBOT_POS_H
#define VERYSMALL_MESSAGE_FIVE_ROBOT_POS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace verysmall
{
template <class ContainerAllocator>
struct five_robot_pos_
{
  typedef five_robot_pos_<ContainerAllocator> Type;

  five_robot_pos_()
    : robot_pos_1()
    , robot_pos_2()
    , robot_pos_3()
    , robot_pos_4()
    , robot_pos_5()  {
      robot_pos_1.assign(0);

      robot_pos_2.assign(0);

      robot_pos_3.assign(0);

      robot_pos_4.assign(0);

      robot_pos_5.assign(0);
  }
  five_robot_pos_(const ContainerAllocator& _alloc)
    : robot_pos_1()
    , robot_pos_2()
    , robot_pos_3()
    , robot_pos_4()
    , robot_pos_5()  {
  (void)_alloc;
      robot_pos_1.assign(0);

      robot_pos_2.assign(0);

      robot_pos_3.assign(0);

      robot_pos_4.assign(0);

      robot_pos_5.assign(0);
  }



   typedef boost::array<uint32_t, 2>  _robot_pos_1_type;
  _robot_pos_1_type robot_pos_1;

   typedef boost::array<uint32_t, 2>  _robot_pos_2_type;
  _robot_pos_2_type robot_pos_2;

   typedef boost::array<uint32_t, 2>  _robot_pos_3_type;
  _robot_pos_3_type robot_pos_3;

   typedef boost::array<uint32_t, 2>  _robot_pos_4_type;
  _robot_pos_4_type robot_pos_4;

   typedef boost::array<uint32_t, 2>  _robot_pos_5_type;
  _robot_pos_5_type robot_pos_5;





  typedef boost::shared_ptr< ::verysmall::five_robot_pos_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::verysmall::five_robot_pos_<ContainerAllocator> const> ConstPtr;

}; // struct five_robot_pos_

typedef ::verysmall::five_robot_pos_<std::allocator<void> > five_robot_pos;

typedef boost::shared_ptr< ::verysmall::five_robot_pos > five_robot_posPtr;
typedef boost::shared_ptr< ::verysmall::five_robot_pos const> five_robot_posConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::verysmall::five_robot_pos_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::verysmall::five_robot_pos_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace verysmall

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'verysmall': ['/home/marquesman/ararabots/src/verysmall/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::verysmall::five_robot_pos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::verysmall::five_robot_pos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::verysmall::five_robot_pos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::verysmall::five_robot_pos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::verysmall::five_robot_pos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::verysmall::five_robot_pos_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::verysmall::five_robot_pos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2fb152bde934739c2e0092eef499be2d";
  }

  static const char* value(const ::verysmall::five_robot_pos_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2fb152bde934739cULL;
  static const uint64_t static_value2 = 0x2e0092eef499be2dULL;
};

template<class ContainerAllocator>
struct DataType< ::verysmall::five_robot_pos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "verysmall/five_robot_pos";
  }

  static const char* value(const ::verysmall::five_robot_pos_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::verysmall::five_robot_pos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32[2]    robot_pos_1\n\
uint32[2]    robot_pos_2\n\
uint32[2]    robot_pos_3\n\
uint32[2]    robot_pos_4\n\
uint32[2]    robot_pos_5\n\
";
  }

  static const char* value(const ::verysmall::five_robot_pos_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::verysmall::five_robot_pos_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robot_pos_1);
      stream.next(m.robot_pos_2);
      stream.next(m.robot_pos_3);
      stream.next(m.robot_pos_4);
      stream.next(m.robot_pos_5);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct five_robot_pos_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::verysmall::five_robot_pos_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::verysmall::five_robot_pos_<ContainerAllocator>& v)
  {
    s << indent << "robot_pos_1[]" << std::endl;
    for (size_t i = 0; i < v.robot_pos_1.size(); ++i)
    {
      s << indent << "  robot_pos_1[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.robot_pos_1[i]);
    }
    s << indent << "robot_pos_2[]" << std::endl;
    for (size_t i = 0; i < v.robot_pos_2.size(); ++i)
    {
      s << indent << "  robot_pos_2[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.robot_pos_2[i]);
    }
    s << indent << "robot_pos_3[]" << std::endl;
    for (size_t i = 0; i < v.robot_pos_3.size(); ++i)
    {
      s << indent << "  robot_pos_3[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.robot_pos_3[i]);
    }
    s << indent << "robot_pos_4[]" << std::endl;
    for (size_t i = 0; i < v.robot_pos_4.size(); ++i)
    {
      s << indent << "  robot_pos_4[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.robot_pos_4[i]);
    }
    s << indent << "robot_pos_5[]" << std::endl;
    for (size_t i = 0; i < v.robot_pos_5.size(); ++i)
    {
      s << indent << "  robot_pos_5[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.robot_pos_5[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // VERYSMALL_MESSAGE_FIVE_ROBOT_POS_H
